apiVersion: v1
kind: Service
metadata:
  name: name-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: name-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nameApi.replicas }}
  selector:
    matchLabels:
      app: name-api
  template:
    metadata:
      labels:
        app: name-api
    spec:
      containers:
      - name: name-api
        image: k8scourse/module6-name-api:{{ .Values.nameApi.imageTag }}
        ports:
        - containerPort: 8080
        resources:
