# version number of the package in the format major.minor.patch
version: '3.7'

# services contains the services that make up the application
services:
  # The first service is the web service
  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        buildversion: 1
        PACKAGES: 'nano wget curl'
    ports:
      - '3000:3000'
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on:
      - mongodb

  # The second service is the database service
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network

# networks contains the networks that make up the application
networks:
  nodeapp-network:
    driver: bridge
