apiVersion: v1
kind: Namespace
metadata:
  name: statefulset-demo

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: statefulset-demo
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: statefulset-demo
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  # minReadySeconds: 3 # by default is 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 50Mi
