apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: sidecar-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 80
        resources:
        volumeMounts:
          - name: shared-logs
            mountPath: /var/log/nginx
      - name: log-sidecar
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "tail -n+1 -f /var/log/nginx/access.log"]
        volumeMounts:
          - name: shared-logs
            mountPath: /var/log/nginx
