version: '3.4'

services:
  carvedrock.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    

  carvedrock.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    


  carvedrock.orderprocessor:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
