FROM node:alpine AS build

RUN apk --no-cache add curl

WORKDIR /usr/app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx

COPY --from=build /usr/app/dist /usr/share/nginx/html
