apiVersion: v1
kind: Namespace
metadata:
  name: rbac-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: rbac-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
