apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-demo
  namespace: node-scheduling-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "disk"
                operator: "In"
                values:
                - "ssd"
      containers:
      - name: nginx
        image: nginx
        resources:
