apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selection-demo
  namespace: node-scheduling-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: nginx
        image: nginx
        resources:
