# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.local
    ingressClassName: nginx

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
