apiVersion: v1
kind: Namespace
metadata:
  name: job-demo

---

apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: job-demo
spec:
  template:
    spec:
      containers:
      - name: job-demo-console-app
        image: k8scourse/module9-job-demo-console-app:1
        # args: ["simulateError"]
      restartPolicy: Never
  # completions: 2
  # parallelism: 2
  # backoffLimit: 3
  # ttlSecondsAfterFinished: 60
  # completionMode: Indexed # Only valid with parallelism >1 and with a completions value.
                            # Sets zero-based JOB_COMPLETION_INDEX environment variable in the container.
