apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: health-check-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: k8scourse/health-checks:4
        ports:
        - containerPort: 8080
        resources:
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
          # grpc:
          #   port: 2379
          # tcpSocket:
          #   port: 8080
          # exec:
          #   command:
          #   - cat
          #   - /tmp/healthy
        # startupProbe:
        #   httpGet:
        #     path: /startup
        #     port: 8080
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   periodSeconds: 10
        #   failureThreshold: 30
